from enum import Enum


class ActionIds(Enum):

    ACTION_CHARACTER_CHANGE_MAP: int = 2

    ACTION_CHARACTER_CHANGE_RESPAWN_MAP: int = 3

    ACTION_CHARACTER_TELEPORT_ON_SAME_MAP: int = 4

    ACTION_CHARACTER_PUSH: int = 5

    ACTION_CHARACTER_PULL: int = 6

    ACTION_CHARACTER_DIVORCE_WIFE_OR_HUSBAND: int = 7

    ACTION_CHARACTER_EXCHANGE_PLACES: int = 8

    ACTION_CHARACTER_DODGE_HIT: int = 9

    ACTION_CHARACTER_LEARN_EMOTICON: int = 10

    ACTION_CHARACTER_CREATE_GUILD: int = 12

    ACTION_QUEST_OBJECTIVE_VALIDATE: int = 30

    ACTION_QUEST_STEP_VALIDATE: int = 31

    ACTION_QUEST_QUEST_VALIDATE: int = 32

    ACTION_QUEST_START: int = 34

    ACTION_QUEST_RESET: int = 36

    ACTION_QUEST_FORCE_START: int = 37

    ACTION_BREACH_CREATE: int = 46

    ACTION_BREACH_ENTER: int = 47

    ACTION_BREACH_NEXT_FIGHT_ROOM: int = 48

    ACTION_BREACH_NEXT_SAFE_ROOM: int = 49

    ACTION_CARRY_CHARACTER: int = 50

    ACTION_THROW_CARRIED_CHARACTER: int = 51

    ACTION_BREACH_PREVIOUS_ROOM: int = 52

    ACTION_BREACH_JUMP_TO_SAFE_ROOM: int = 53

    ACTION_BREACH_KICK_OUT: int = 54

    ACTION_BREACH_MODIFY_MAP: int = 55

    ACTION_BREACH_DISPLAY_ROOMS_REWARDS: int = 56

    ACTION_BREACH_GAIN_BONUS: int = 57

    ACTION_BREACH_MODIFY_ROOM: int = 58

    ACTION_BREACH_REMOVE_EROSION: int = 59

    ACTION_BREACH_MODIFY_FIGHT_MODIFIER: int = 60

    ACTION_BREACH_MODIFY_BOSS: int = 61

    ACTION_BREACH_ADD_BOSS: int = 62

    ACTION_ANOMALY_EXIT: int = 63

    ACTION_CHARACTER_MOVEMENT_POINTS_STEAL: int = 77

    ACTION_CHARACTER_MOVEMENT_POINTS_WIN: int = 78

    ACTION_CHARACTER_MULTIPLY_RECEIVED_DAMAGE_OR_GIVE_LIFE_WITH_RATIO: int = 79

    ACTION_CHARACTER_LIFE_POINTS_LOST_FROM_PUSH: int = 80

    ACTION_CHARACTER_LIFE_POINTS_WIN_WITHOUT_ELEMENT: int = 81

    ACTION_CHARACTER_LIFE_POINTS_STEAL_WITHOUT_BOOST: int = 82

    ACTION_CHARACTER_ACTION_POINTS_STEAL: int = 84

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_CASTER_LIFE_FROM_WATER: int = 85

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_CASTER_LIFE_FROM_EARTH: int = 86

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_CASTER_LIFE_FROM_AIR: int = 87

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_CASTER_LIFE_FROM_FIRE: int = 88

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_CASTER_LIFE: int = 89

    ACTION_CHARACTER_DISPATCH_LIFE_POINTS_PERCENT: int = 90

    ACTION_CHARACTER_LIFE_POINTS_STEAL_FROM_WATER: int = 91

    ACTION_CHARACTER_LIFE_POINTS_STEAL_FROM_EARTH: int = 92

    ACTION_CHARACTER_LIFE_POINTS_STEAL_FROM_AIR: int = 93

    ACTION_CHARACTER_LIFE_POINTS_STEAL_FROM_FIRE: int = 94

    ACTION_CHARACTER_LIFE_POINTS_STEAL: int = 95

    ACTION_CHARACTER_LIFE_POINTS_LOST_FROM_WATER: int = 96

    ACTION_CHARACTER_LIFE_POINTS_LOST_FROM_EARTH: int = 97

    ACTION_CHARACTER_LIFE_POINTS_LOST_FROM_AIR: int = 98

    ACTION_CHARACTER_LIFE_POINTS_LOST_FROM_FIRE: int = 99

    ACTION_CHARACTER_LIFE_POINTS_LOST: int = 100

    ACTION_CHARACTER_ACTION_POINTS_LOST: int = 101

    ACTION_CHARACTER_LIFE_LOST_MODERATOR: int = 105

    ACTION_CHARACTER_SPELL_REFLECTOR: int = 106

    ACTION_CHARACTER_LIFE_LOST_REFLECTOR: int = 107

    ACTION_CHARACTER_LIFE_POINTS_WIN: int = 108

    ACTION_CHARACTER_LIFE_POINTS_LOST_CASTER: int = 109

    ACTION_CHARACTER_BOOST_LIFE_POINTS: int = 110

    ACTION_CHARACTER_BOOST_ACTION_POINTS: int = 111

    ACTION_CHARACTER_BOOST_DAMAGES: int = 112

    ACTION_CHARACTER_MULTIPLY_DAMAGES: int = 114

    ACTION_CHARACTER_BOOST_CRITICAL_HIT: int = 115

    ACTION_CHARACTER_DEBOOST_RANGE: int = 116

    ACTION_CHARACTER_BOOST_RANGE: int = 117

    ACTION_CHARACTER_BOOST_STRENGTH: int = 118

    ACTION_CHARACTER_BOOST_AGILITY: int = 119

    ACTION_CHARACTER_ACTION_POINTS_WIN: int = 120

    ACTION_CHARACTER_BOOST_DAMAGES_FOR_ALL_GAME: int = 121

    ACTION_CHARACTER_BOOST_CRITICAL_MISS: int = 122

    ACTION_CHARACTER_BOOST_CHANCE: int = 123

    ACTION_CHARACTER_BOOST_WISDOM: int = 124

    ACTION_CHARACTER_BOOST_VITALITY: int = 125

    ACTION_CHARACTER_BOOST_INTELLIGENCE: int = 126

    ACTION_CHARACTER_MOVEMENT_POINTS_LOST: int = 127

    ACTION_CHARACTER_BOOST_MOVEMENT_POINTS: int = 128

    ACTION_CHARACTER_STEAL_GOLD: int = 130

    ACTION_CHARACTER_REMOVE_ALL_EFFECTS: int = 132

    ACTION_CHARACTER_ACTION_POINTS_LOST_CASTER: int = 133

    ACTION_CHARACTER_MOVEMENT_POINTS_LOST_CASTER: int = 134

    ACTION_CHARACTER_DEBOOST_RANGE_CASTER: int = 135

    ACTION_CHARACTER_BOOST_RANGE_CASTER: int = 136

    ACTION_CHARACTER_BOOST_DAMAGES_CASTER: int = 137

    ACTION_CHARACTER_BOOST_DAMAGES_PERCENT: int = 138

    ACTION_CHARACTER_ENERGY_POINTS_WIN: int = 139

    ACTION_CHARACTER_PASS_NEXT_TURN: int = 140

    ACTION_CHARACTER_KILL: int = 141

    ACTION_CHARACTER_BOOST_PHYSICAL_DAMAGES: int = 142

    ACTION_CHARACTER_LIFE_POINTS_WIN_WITHOUT_BOOST: int = 143

    ACTION_CHARACTER_LIFE_POINTS_LOST_NO_BOOST: int = 144

    ACTION_CHARACTER_DEBOOST_DAMAGES: int = 145

    ACTION_CHARACTER_CURSE: int = 146

    ACTION_CHARACTER_RESURECT_ALLY_IN_FIGHT: int = 147

    ACTION_CHARACTER_ADD_FOLLOWING_CHARACTER: int = 148

    ACTION_CHARACTER_CHANGE_LOOK: int = 149

    ACTION_CHARACTER_MAKE_INVISIBLE: int = 150

    ACTION_CHARACTER_DEBOOST_CHANCE: int = 152

    ACTION_CHARACTER_DEBOOST_VITALITY: int = 153

    ACTION_CHARACTER_DEBOOST_AGILITY: int = 154

    ACTION_CHARACTER_DEBOOST_INTELLIGENCE: int = 155

    ACTION_CHARACTER_DEBOOST_WISDOM: int = 156

    ACTION_CHARACTER_DEBOOST_STRENGTH: int = 157

    ACTION_CHARACTER_BOOST_MAXIMUM_WEIGHT: int = 158

    ACTION_CHARACTER_DEBOOST_MAXIMUM_WEIGHT: int = 159

    ACTION_CHARACTER_BOOST_ACTION_POINTS_LOST_DODGE: int = 160

    ACTION_CHARACTER_BOOST_MOVEMENT_POINTS_LOST_DODGE: int = 161

    ACTION_CHARACTER_DEBOOST_ACTION_POINTS_LOST_DODGE: int = 162

    ACTION_CHARACTER_DEBOOST_MOVEMENT_POINTS_LOST_DODGE: int = 163

    ACTION_CHARACTER_BOOST_ONE_WEAPON_DAMAGE_PERCENT: int = 165

    ACTION_CHARACTER_DEBOOST_ACTION_POINTS: int = 168

    ACTION_CHARACTER_DEBOOST_MOVEMENT_POINTS: int = 169

    ACTION_CHARACTER_DEBOOST_CRITICAL_HIT: int = 171

    ACTION_CHARACTER_DEBOOST_MAGICAL_REDUCTION: int = 172

    ACTION_CHARACTER_DEBOOST_PHYSICAL_REDUCTION: int = 173

    ACTION_CHARACTER_BOOST_INITIATIVE: int = 174

    ACTION_CHARACTER_DEBOOST_INITIATIVE: int = 175

    ACTION_CHARACTER_BOOST_MAGIC_FIND: int = 176

    ACTION_CHARACTER_DEBOOST_MAGIC_FIND: int = 177

    ACTION_CHARACTER_BOOST_HEAL_BONUS: int = 178

    ACTION_CHARACTER_DEBOOST_HEAL_BONUS: int = 179

    ACTION_CHARACTER_ADD_DOUBLE_USE_SUMMON_SLOT: int = 180

    ACTION_SUMMON_CREATURE: int = 181

    ACTION_CHARACTER_BOOST_MAXIMUM_SUMMONED_CREATURES: int = 182

    ACTION_CHARACTER_BOOST_MAGICAL_REDUCTION: int = 183

    ACTION_CHARACTER_BOOST_PHYSICAL_REDUCTION: int = 184

    ACTION_CHARACTER_DEBOOST_DAMAGES_PERCENT: int = 186

    ACTION_CHARACTER_ALIGNMENT_SIDE_SET: int = 188

    ACTION_CHARACTER_INVENTORY_REMOVE_ITEM: int = 192

    ACTION_CHARACTER_INVENTORY_ADD_ITEM_CHECK: int = 193

    ACTION_CHARACTER_INVENTORY_GAIN_KAMAS: int = 194

    ACTION_CHARACTER_TRANSFORM: int = 197

    ACTION_DECORS_ADD_OBJECT: int = 201

    ACTION_DECORS_REVEAL_UNVISIBLE: int = 202

    ACTION_CHARACTER_RESURRECTION: int = 206

    ACTION_CHARACTER_BOOST_EARTH_ELEMENT_PERCENT: int = 210

    ACTION_CHARACTER_BOOST_WATER_ELEMENT_PERCENT: int = 211

    ACTION_CHARACTER_BOOST_AIR_ELEMENT_PERCENT: int = 212

    ACTION_CHARACTER_BOOST_FIRE_ELEMENT_PERCENT: int = 213

    ACTION_CHARACTER_BOOST_NEUTRAL_ELEMENT_PERCENT: int = 214

    ACTION_CHARACTER_DEBOOST_EARTH_ELEMENT_PERCENT: int = 215

    ACTION_CHARACTER_DEBOOST_WATER_ELEMENT_PERCENT: int = 216

    ACTION_CHARACTER_DEBOOST_AIR_ELEMENT_PERCENT: int = 217

    ACTION_CHARACTER_DEBOOST_FIRE_ELEMENT_PERCENT: int = 218

    ACTION_CHARACTER_DEBOOST_NEUTRAL_ELEMENT_PERCENT: int = 219

    ACTION_CHARACTER_REFLECTOR_UNBOOSTED: int = 220

    ACTION_CHARACTER_INVENTORY_ADD_ITEM_RANDOM_NOCHECK: int = 221

    ACTION_CHARACTER_INVENTORY_ADD_ITEM_FROM_RANDOM_DROP: int = 222

    ACTION_CHARACTER_BOOST_TRAP: int = 225

    ACTION_CHARACTER_BOOST_TRAP_PERCENT: int = 226

    ACTION_CHARACTER_GAIN_RIDE: int = 229

    ACTION_CHARACTER_ENERGY_LOSS_BOOST: int = 230

    ACTION_DECORS_PLAY_ANIMATION_D2: int = 237

    ACTION_PLAY_CINEMATIC: int = 239

    ACTION_CHARACTER_BOOST_EARTH_ELEMENT_RESIST: int = 240

    ACTION_CHARACTER_BOOST_WATER_ELEMENT_RESIST: int = 241

    ACTION_CHARACTER_BOOST_AIR_ELEMENT_RESIST: int = 242

    ACTION_CHARACTER_BOOST_FIRE_ELEMENT_RESIST: int = 243

    ACTION_CHARACTER_BOOST_NEUTRAL_ELEMENT_RESIST: int = 244

    ACTION_CHARACTER_DEBOOST_EARTH_ELEMENT_RESIST: int = 245

    ACTION_CHARACTER_DEBOOST_WATER_ELEMENT_RESIST: int = 246

    ACTION_CHARACTER_DEBOOST_AIR_ELEMENT_RESIST: int = 247

    ACTION_CHARACTER_DEBOOST_FIRE_ELEMENT_RESIST: int = 248

    ACTION_CHARACTER_DEBOOST_NEUTRAL_ELEMENT_RESIST: int = 249

    ACTION_CHARACTER_BOOST_EARTH_ELEMENT_PVP_PERCENT: int = 250

    ACTION_CHARACTER_BOOST_WATER_ELEMENT_PVP_PERCENT: int = 251

    ACTION_CHARACTER_BOOST_AIR_ELEMENT_PVP_PERCENT: int = 252

    ACTION_CHARACTER_BOOST_FIRE_ELEMENT_PVP_PERCENT: int = 253

    ACTION_CHARACTER_BOOST_NEUTRAL_ELEMENT_PVP_PERCENT: int = 254

    ACTION_CHARACTER_DEBOOST_EARTH_ELEMENT_PVP_PERCENT: int = 255

    ACTION_CHARACTER_DEBOOST_WATER_ELEMENT_PVP_PERCENT: int = 256

    ACTION_CHARACTER_DEBOOST_AIR_ELEMENT_PVP_PERCENT: int = 257

    ACTION_CHARACTER_DEBOOST_FIRE_ELEMENT_PVP_PERCENT: int = 258

    ACTION_CHARACTER_DEBOOST_NEUTRAL_ELEMENT_PVP_PERCENT: int = 259

    ACTION_CHARACTER_BOOST_EARTH_ELEMENT_PVP_RESIST: int = 260

    ACTION_CHARACTER_BOOST_WATER_ELEMENT_PVP_RESIST: int = 261

    ACTION_CHARACTER_BOOST_AIR_ELEMENT_PVP_RESIST: int = 262

    ACTION_CHARACTER_BOOST_FIRE_ELEMENT_PVP_RESIST: int = 263

    ACTION_CHARACTER_BOOST_NEUTRAL_ELEMENT_PVP_RESIST: int = 264

    ACTION_CHARACTER_LIFE_LOST_CASTER_MODERATOR: int = 265

    ACTION_CHARACTER_STEAL_CHANCE: int = 266

    ACTION_CHARACTER_STEAL_VITALITY: int = 267

    ACTION_CHARACTER_STEAL_AGILITY: int = 268

    ACTION_CHARACTER_STEAL_INTELLIGENCE: int = 269

    ACTION_CHARACTER_STEAL_WISDOM: int = 270

    ACTION_CHARACTER_STEAL_STRENGTH: int = 271

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_CASTER_LIFE_MISSING_FROM_WATER: int = 275

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_CASTER_LIFE_MISSING_FROM_EARTH: int = 276

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_CASTER_LIFE_MISSING_FROM_AIR: int = 277

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_CASTER_LIFE_MISSING_FROM_FIRE: int = 278

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_CASTER_LIFE_MISSING: int = 279

    ACTION_BOOST_SPELL_RANGE_MIN: int = 280

    ACTION_BOOST_SPELL_RANGE_MAX: int = 281

    ACTION_BOOST_SPELL_RANGEABLE: int = 282

    ACTION_BOOST_SPELL_DMG: int = 283

    ACTION_BOOST_SPELL_HEAL: int = 284

    ACTION_BOOST_SPELL_AP_COST: int = 285

    ACTION_BOOST_SPELL_CAST_INTVL: int = 286

    ACTION_BOOST_SPELL_CC: int = 287

    ACTION_BOOST_SPELL_CASTOUTLINE: int = 288

    ACTION_BOOST_SPELL_NOLINEOFSIGHT: int = 289

    ACTION_BOOST_SPELL_MAXPERTURN: int = 290

    ACTION_BOOST_SPELL_MAXPERTARGET: int = 291

    ACTION_BOOST_SPELL_CAST_INTVL_SET: int = 292

    ACTION_BOOST_SPELL_BASE_DMG: int = 293

    ACTION_DEBOOST_SPELL_RANGE_MAX: int = 294

    ACTION_DEBOOST_SPELL_RANGE_MIN: int = 295

    ACTION_DEBOOST_SPELL_AP_COST: int = 296

    ACTION_FIGHT_DISPELL_TEMPORARY_OBJECT: int = 310

    ACTION_CHARACTER_STEAL_RANGE: int = 320

    ACTION_CHARACTER_CHANGE_COLOR: int = 333

    ACTION_CHARACTER_ADD_APPEARANCE: int = 335

    ACTION_REFRESH_MAP_NPC_ONLY_FOR_ME_IN_ROLEPLAY: int = 350

    ACTION_REFRESH_MAP_NPC_FOR_EVERYONE_IN_ROLEPLAY: int = 351

    ACTION_FIGHT_ADD_TRAP_CASTING_SPELL: int = 400

    ACTION_FIGHT_ADD_GLYPH_CASTING_SPELL: int = 401

    ACTION_FIGHT_ADD_GLYPH_CASTING_SPELL_ENDTURN: int = 402

    ACTION_FIGHT_KILL_AND_SUMMON: int = 405

    ACTION_CHARACTER_DISPELL_SPELL: int = 406

    ACTION_CHARACTER_LIFE_POINTS_WIN_NO_BOOST: int = 407

    ACTION_CHARACTER_BOOST_AP_ATTACK: int = 410

    ACTION_CHARACTER_DEBOOST_AP_ATTACK: int = 411

    ACTION_CHARACTER_BOOST_MP_ATTACK: int = 412

    ACTION_CHARACTER_DEBOOST_MP_ATTACK: int = 413

    ACTION_CHARACTER_BOOST_PUSH_DAMAGE: int = 414

    ACTION_CHARACTER_DEBOOST_PUSH_DAMAGE: int = 415

    ACTION_CHARACTER_BOOST_PUSH_DAMAGE_REDUCTION: int = 416

    ACTION_CHARACTER_DEBOOST_PUSH_DAMAGE_REDUCTION: int = 417

    ACTION_CHARACTER_BOOST_CRITICAL_DAMAGES_BONUS: int = 418

    ACTION_CHARACTER_DEBOOST_CRITICAL_DAMAGES_BONUS: int = 419

    ACTION_CHARACTER_BOOST_CRITICAL_DAMAGES_REDUCTION: int = 420

    ACTION_CHARACTER_DEBOOST_CRITICAL_DAMAGES_REDUCTION: int = 421

    ACTION_CHARACTER_BOOST_EARTH_DAMAGES: int = 422

    ACTION_CHARACTER_DEBOOST_EARTH_DAMAGES: int = 423

    ACTION_CHARACTER_BOOST_FIRE_DAMAGES: int = 424

    ACTION_CHARACTER_DEBOOST_FIRE_DAMAGES: int = 425

    ACTION_CHARACTER_BOOST_WATER_DAMAGES: int = 426

    ACTION_CHARACTER_DEBOOST_WATER_DAMAGES: int = 427

    ACTION_CHARACTER_BOOST_AIR_DAMAGES: int = 428

    ACTION_CHARACTER_DEBOOST_AIR_DAMAGES: int = 429

    ACTION_CHARACTER_BOOST_NEUTRAL_DAMAGES: int = 430

    ACTION_CHARACTER_DEBOOST_NEUTRAL_DAMAGES: int = 431

    ACTION_CHARACTER_ACTION_POINTS_STEAL_NO_EVADE: int = 440

    ACTION_CHARACTER_MOVEMENT_POINTS_STEAL_NO_EVADE: int = 441

    ACTION_CHANGE_COMPASS_BY_COORD: int = 509

    ACTION_ADD_PRISM: int = 513

    ACTION_SHOW_TAX_COLLECTOR_LIST: int = 516

    ACTION_EXCHANGE_DECRAFT_OPEN: int = 517

    ACTION_GOTO_WAYPOINT: int = 600

    ACTION_CHARACTER_LEARN_JOB: int = 603

    ACTION_CHARACTER_LEARN_SPELL_LEVEL: int = 604

    ACTION_CHARACTER_GAIN_XP: int = 605

    ACTION_CHARACTER_GAIN_WISDOM: int = 606

    ACTION_CHARACTER_GAIN_STRENGTH: int = 607

    ACTION_CHARACTER_GAIN_CHANCE: int = 608

    ACTION_CHARACTER_GAIN_AGILITY: int = 609

    ACTION_CHARACTER_GAIN_VITALITY: int = 610

    ACTION_CHARACTER_GAIN_INTELLIGENCE: int = 611

    ACTION_CHARACTER_GAIN_STATS_POINTS: int = 612

    ACTION_CHARACTER_GAIN_JOB_XP: int = 614

    ACTION_CHARACTER_UNLEARN_JOB: int = 615

    ACTION_CHARACTER_READ_BOOK: int = 620

    ACTION_CHARACTER_SUMMON_MONSTER: int = 621

    ACTION_GOTO_HOUSE: int = 622

    ACTION_CHARACTER_SUMMON_MONSTER_GROUP: int = 623

    ACTION_CHARACTER_UNLEARN_GUILDSPELL: int = 624

    ACTION_CHARACTER_RESET_CHARACS: int = 626

    ACTION_CHARACTER_SUMMON_MONSTER_GROUP_SET_MAP: int = 627

    ACTION_CHARACTER_SUMMON_MONSTER_GROUP_DYNAMIC: int = 628

    ACTION_CHARACTER_LEARN_SPELL: int = 629

    ACTION_CHARACTER_SEND_INFORMATION_TEXT: int = 630

    ACTION_CHARACTER_SEND_ERROR_TEXT: int = 632

    ACTION_CHARACTER_GAIN_HONOUR: int = 640

    ACTION_CHARACTER_GAIN_DISHONOUR: int = 641

    ACTION_CHARACTER_LOOSE_HONOUR: int = 642

    ACTION_CHARACTER_LOOSE_DISHONOUR: int = 643

    ACTION_MAP_RESURECTION_ALLIES: int = 645

    ACTION_MAP_HEAL_ALLIES: int = 646

    ACTION_MAP_FORCE_ENNEMIES_GHOST: int = 647

    ACTION_FORCE_ENNEMY_GHOST: int = 648

    ACTION_FAKE_ALIGNMENT: int = 649

    ACTION_SET_STATED_ELEMENT_STATE: int = 652

    ACTION_INSTANCIEDMAP_LEAVE: int = 654

    ACTION_NOOP: int = 666

    ACTION_KILL_FIGHT: int = 667

    ACTION_INCARNATION: int = 669

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_CASTER_LIFE_REDUCED_BY_CASTER: int = 670

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_CASTER_LIFE_NOT_REDUCED: int = 671

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_CASTER_LIFE_MIDLIFE: int = 672

    ACTION_CHARACTER_REFERENCEMENT: int = 699

    ACTION_ITEM_CHANGE_EFFECT: int = 700

    ACTION_ITEM_ADD_EFFECT: int = 701

    ACTION_ITEM_ADD_DURABILITY: int = 702

    ACTION_CAPTURE_SOUL: int = 705

    ACTION_CAPTURE_RIDE: int = 706

    ACTION_ITEM_EQUIP_PRESET: int = 707

    ACTION_CHARACTER_ADD_COST_TO_ACTION: int = 710

    ACTION_LADDER_SUPERRACE: int = 715

    ACTION_LADDER_RACE: int = 716

    ACTION_LADDER_ID: int = 717

    ACTION_PVP_LADDER: int = 720

    ACTION_CHARACTER_LEARN_SPELL_TEMPORARY: int = 722

    ACTION_GAIN_TITLE: int = 724

    ACTION_CHARACTER_RENAME_INVALID_GUILD: int = 725

    ACTION_GAIN_ORNAMENT: int = 726

    ACTION_TELEPORT_NEAREST_PRISM: int = 730

    ACTION_AUTO_AGGRESS_ENEMY_PLAYER: int = 731

    ACTION_RESIST_AUTO_AGGRESS: int = 732

    ACTION_SHUSHU_STACK_RUNE_WEAPON: int = 740

    ACTION_SHUSHU_STOCKED_RUNE: int = 741

    ACTION_SHUSHU_STACK_RUNE: int = 742

    ACTION_BOOST_SOUL_CAPTURE_BONUS: int = 750

    ACTION_BOOST_RIDE_XP_BONUS: int = 751

    ACTION_CHARACTER_BOOST_TAKLE_EVADE: int = 752

    ACTION_CHARACTER_BOOST_TAKLE_BLOCK: int = 753

    ACTION_CHARACTER_DEBOOST_TAKLE_EVADE: int = 754

    ACTION_CHARACTER_DEBOOST_TAKLE_BLOCK: int = 755

    ACTION_REMOVE_ON_MOVE: int = 760

    ACTION_CHARACTER_SACRIFY: int = 765

    ACTION_CLOCKWISE_CONFUSION_DEGREE: int = 770

    ACTION_CLOCKWISE_CONFUSION_PI_2: int = 771

    ACTION_CLOCKWISE_CONFUSION_PI_4: int = 772

    ACTION_COUNTER_CLOCKWISE_CONFUSION_DEGREE: int = 773

    ACTION_COUNTER_CLOCKWISE_CONFUSION_PI_2: int = 774

    ACTION_COUNTER_CLOCKWISE_CONFUSION_PI_4: int = 775

    ACTION_CHARACTER_BOOST_PERMANENT_DAMAGE_PERCENT: int = 776

    ACTION_CHARACTER_CHANGE_RESPAWN_MAP_BY_REF: int = 778

    ACTION_CHARACTER_TELEPORT_ON_PREVIOUS_MAP: int = 779

    ACTION_CHARACTER_SUMMON_DEAD_ALLY_IN_FIGHT: int = 780

    ACTION_CHARACTER_UNLUCKY: int = 781

    ACTION_CHARACTER_MAXIMIZE_ROLL: int = 782

    ACTION_CHARACTER_PUSH_UP_TO: int = 783

    ACTION_CHARACTER_TELEPORT_TO_FIGHT_START_POS: int = 784

    ACTION_CHARACTER_WALK_FOUR_DIR: int = 785

    ACTION_CHARACTER_HEAL_ATTACKERS: int = 786

    ACTION_CHARACTER_PUNISHMENT: int = 788

    ACTION_CHARACTER_LOOSE_ALL_ITEMS_FROM_CATEGORY: int = 789

    ACTION_FIND_BOUNTY_TARGET: int = 790

    ACTION_MARK_TARGET_MERCENARY: int = 791

    ACTION_TARGET_EXECUTE_SPELL: int = 792

    ACTION_TARGET_EXECUTE_SPELL_WITH_ANIMATION: int = 793

    ACTION_HUNT_TOOL: int = 795

    ACTION_CHARACTER_RESTORE_RESPAWN_MAP: int = 796

    ACTION_ITEM_CHANGE_DURATION: int = 805

    ACTION_ITEM_PETS_SHAPE: int = 806

    ACTION_ITEM_PETS_EAT: int = 807

    ACTION_PETS_LAST_MEAL: int = 808

    ACTION_SIZE: int = 810

    ACTION_ITEM_BUFF_CHANGE_DURATION: int = 811

    ACTION_ITEM_CHANGE_DURABILITY: int = 812

    ACTION_ITEM_UPDATE_DATE: int = 813

    ACTION_ITEM_DUNGEON_KEY_DATE: int = 814

    ACTION_ITEM_FM_LOST_POWER: int = 815

    ACTION_ITEM_RESET_DATE: int = 816

    ACTION_ITEM_TELEPORT_FORCE: int = 825

    ACTION_ITEM_TELEPORT_MAP_REFERENCE: int = 826

    ACTION_FIGHT_CHALLENGE_AGAINST_MONSTER: int = 905

    ACTION_FIGHT_CHALLENGE_MIXED_VERSUS_MONSTER: int = 911

    ACTION_CHARACTER_SEND_NOTIFICATION_TEXT: int = 916

    ACTION_CHARACTER_SEND_NOTIFICATION_ALERT_TEXT: int = 917

    ACTION_PET_SET_POWER_BOOST: int = 939

    ACTION_PET_POWER_BOOST: int = 940

    ACTION_FARM_TEMP_WITHDRAW_ITEM: int = 946

    ACTION_FARM_WITHDRAW_ITEM: int = 947

    ACTION_FARM_PLACE_ITEM: int = 948

    ACTION_MOUNT_RIDE: int = 949

    ACTION_FIGHT_SET_STATE: int = 950

    ACTION_FIGHT_UNSET_STATE: int = 951

    ACTION_FIGHT_DISABLE_STATE: int = 952

    ACTION_CREATED_SINCE: int = 963

    ACTION_SHOW_PLAYERNAME: int = 964

    ACTION_ITEM_LIVING_ID: int = 970

    ACTION_ITEM_LIVING_MOOD: int = 971

    ACTION_ITEM_LIVING_SKIN: int = 972

    ACTION_ITEM_LIVING_CATEGORY: int = 973

    ACTION_ITEM_LIVING_LEVEL: int = 974

    ACTION_MARK_NEVER_TRADABLE_STRONG: int = 981

    ACTION_MARK_NEVER_TRADABLE: int = 982

    ACTION_MARK_NOT_TRADABLE: int = 983

    ACTION_MARK_LEGIT_OWNER: int = 984

    ACTION_SET_CRAFTERMAGE: int = 985

    ACTION_MARK_TARGET: int = 986

    ACTION_SET_OWNER: int = 987

    ACTION_SET_CRAFTER: int = 988

    ACTION_SEEK_TARGET: int = 989

    ACTION_SHOW_TEXT: int = 990

    ACTION_RIDE_INVALID: int = 994

    ACTION_RIDE_DETAILS: int = 995

    ACTION_ITEM_TELEPORT: int = 999

    ACTION_FARM_OBJET_EFFICACITY: int = 1007

    ACTION_SUMMON_BOMB: int = 1008

    ACTION_CHARACTER_ACTIVATE_BOMB: int = 1009

    ACTION_SUMMON_SLAVE: int = 1011

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_MOVEMENT_POINTS: int = 1012

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_MOVEMENT_POINTS_FROM_AIR: int = 1013

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_MOVEMENT_POINTS_FROM_WATER: int = 1014

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_MOVEMENT_POINTS_FROM_FIRE: int = 1015

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_MOVEMENT_POINTS_FROM_EARTH: int = 1016

    ACTION_TARGET_EXECUTE_SPELL_ON_SOURCE: int = 1017

    ACTION_SOURCE_EXECUTE_SPELL_ON_TARGET: int = 1018

    ACTION_SOURCE_EXECUTE_SPELL_ON_SOURCE: int = 1019

    ACTION_CHARACTER_BOOST_SHIELD_BASED_ON_CASTER_LEVEL: int = 1020

    ACTION_CHARACTER_PUSH_FORCE: int = 1021

    ACTION_CHARACTER_PULL_FORCE: int = 1022

    ACTION_CHARACTER_EXCHANGE_PLACES_FORCE: int = 1023

    ACTION_CHARACTER_ADD_ILLUSION_RANDOM: int = 1024

    ACTION_FORCE_TRAP_TRIGGER: int = 1025

    ACTION_FORCE_GLYPH_TRIGGER: int = 1026

    ACTION_BOMB_COMBO_BONUS: int = 1027

    ACTION_BOMB_TRIGGER_POWDER: int = 1028

    ACTION_CHARACTER_VANISH: int = 1029

    ACTION_FIGHT_ADD_POWDER_CASTING_SPELL: int = 1030

    ACTION_CHARACTER_PASS_CURRENT_TURN: int = 1031

    ACTION_MARK_LEGIT_OWNER_TIMESTAMP: int = 1032

    ACTION_CHARACTER_DEBOOST_VITALITY_PERCENT_STATIC: int = 1033

    ACTION_CHARACTER_SUMMON_DEAD_ALLY_AS_SUMMON_IN_FIGHT: int = 1034

    ACTION_CHARACTER_ADD_SPELL_COOLDOWN: int = 1035

    ACTION_CHARACTER_REMOVE_SPELL_COOLDOWN: int = 1036

    ACTION_CHARACTER_LIFE_POINTS_WIN_ZOBAL: int = 1037

    ACTION_CHARACTER_AURA: int = 1038

    ACTION_CHARACTER_BOOST_SHIELD_BASED_ON_CASTER_LIFE: int = 1039

    ACTION_CHARACTER_BOOST_SHIELD: int = 1040

    ACTION_CHARACTER_GET_PUSHED: int = 1041

    ACTION_CHARACTER_GET_PULLED: int = 1042

    ACTION_CHARACTER_PULL_UP_TO: int = 1043

    ACTION_CHARACTER_PROTECTION_FROM_SPELL: int = 1044

    ACTION_CHARACTER_SET_SPELL_COOLDOWN: int = 1045

    ACTION_CHARACTER_LIFE_POINTS_MALUS: int = 1047

    ACTION_CHARACTER_LIFE_POINTS_MALUS_PERCENT: int = 1048

    ACTION_CHARACTER_GAIN_LEVEL: int = 1049

    ACTION_CHARACTER_EXIT_DUNGEON: int = 1051

    ACTION_CHARACTER_RESUME_DUNGEON: int = 1052

    ACTION_CHARACTER_ENTER_DUNGEON: int = 1053

    ACTION_CHARACTER_BOOST_DAMAGES_PERCENT_SPELLS: int = 1054

    ACTION_CHARACTER_CLEAR_DUNGEON_SAVE: int = 1055

    ACTION_CHARACTER_BOOST_SHIELD_BASED_ON_CASTER_LIFE_TURN_BASED: int = 1056

    ACTION_STATIC_VALUE_MODIFY: int = 1057

    ACTION_STATIC_VALUE_SET: int = 1058

    ACTION_CHARACTER_CUSTOM_MOUNT: int = 1059

    ACTION_CHARACTER_ADD_SCALE_FLAT: int = 1060

    ACTION_CHARACTER_SHARE_DAMAGES: int = 1061

    ACTION_OPEN_URL: int = 1062

    ACTION_CHARACTER_LIFE_POINTS_LOST_NO_BOOST_FROM_EARTH: int = 1063

    ACTION_CHARACTER_LIFE_POINTS_LOST_NO_BOOST_FROM_AIR: int = 1064

    ACTION_CHARACTER_LIFE_POINTS_LOST_NO_BOOST_FROM_WATER: int = 1065

    ACTION_CHARACTER_LIFE_POINTS_LOST_NO_BOOST_FROM_FIRE: int = 1066

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_TARGET_LIFE_FROM_AIR: int = 1067

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_TARGET_LIFE_FROM_WATER: int = 1068

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_TARGET_LIFE_FROM_FIRE: int = 1069

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_TARGET_LIFE_FROM_EARTH: int = 1070

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_TARGET_LIFE: int = 1071

    ACTION_CHARACTER_TAUNT: int = 1072

    ACTION_ITEM_CHANGE_EFFECT_SAFE: int = 1073

    ACTION_MEETING_POINT: int = 1074

    ACTION_CHARACTER_SHORTEN_ACTIVE_EFFECTS_DURATION: int = 1075

    ACTION_CHARACTER_BOOST_RESIST_PERCENT: int = 1076

    ACTION_CHARACTER_DEBOOST_RESIST_PERCENT: int = 1077

    ACTION_CHARACTER_BOOST_VITALITY_PERCENT_STATIC: int = 1078

    ACTION_CHARACTER_DEBOOST_ACTION_POINTS_DODGEABLE: int = 1079

    ACTION_CHARACTER_DEBOOST_MOVEMENT_POINTS_DODGEABLE: int = 1080

    ACTION_ITEM_EXTRA_PODS: int = 1081

    ACTION_ITEM_GIFT_OPEN: int = 1082

    ACTION_ITEM_GIFT_PACKING: int = 1083

    ACTION_ITEM_GIFT_CONTENT: int = 1084

    ACTION_ITEM_GIFT_QUANTITY: int = 1085

    ACTION_ITEM_GIFT_TARGET: int = 1086

    ACTION_ITEM_GIFT_CHOOSE_TARGET: int = 1087

    ACTION_CHARACTER_BOOST_SHIELD_TURN_BASED: int = 1088

    ACTION_FIGHT_ADD_GLYPH_AURA: int = 1091

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_TARGET_MISSING_MAX_LIFE: int = 1092

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_TARGET_MISSING_MAX_LIFE_AIR: int = 1093

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_TARGET_MISSING_MAX_LIFE_FIRE: int = 1094

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_TARGET_MISSING_MAX_LIFE_WATER: int = 1095

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_TARGET_MISSING_MAX_LIFE_EARTH: int = 1096

    ACTION_CHARACTER_ADD_ILLUSION_MIRROR: int = 1097

    ACTION_ITEM_CURSE_USED_ITEM: int = 1098

    ACTION_FIGHT_ROLLBACK_TURN_BEGIN_POSITION: int = 1099

    ACTION_FIGHT_ROLLBACK_PREVIOUS_POSITION: int = 1100

    ACTION_FIGHT_TELESWAP: int = 1101

    ACTION_SPEAKING_ITEM: int = 1102

    ACTION_FIGHT_PUSH_NO_DAMAGE: int = 1103

    ACTION_FIGHT_TELESWAP_MIRROR: int = 1104

    ACTION_FIGHT_TELESWAP_MIRROR_CASTER: int = 1105

    ACTION_FIGHT_TELESWAP_MIRROR_IMPACT_POINT: int = 1106

    ACTION_ITEM_GUILD_RENAME: int = 1107

    ACTION_ITEM_GUILD_EMBLEM_CHANGE: int = 1108

    ACTION_FIGHT_LIFE_POINTS_WIN_PERCENT: int = 1109

    ACTION_ITEM_SUMMON_MONSTER_REWARD_RATE: int = 1110

    ACTION_ITEM_SUMMON_MONSTER_GROUP_MAX_LOOT_SHARES: int = 1111

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_CASTER_MISSING_MAX_LIFE: int = 1118

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_CASTER_MISSING_MAX_LIFE_AIR: int = 1119

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_CASTER_MISSING_MAX_LIFE_FIRE: int = 1120

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_CASTER_MISSING_MAX_LIFE_WATER: int = 1121

    ACTION_CHARACTER_LIFE_POINTS_LOST_BASED_ON_CASTER_MISSING_MAX_LIFE_EARTH: int = 1122

    ACTION_FIGHT_SPLASH_RAW_TAKEN_DAMAGE: int = 1123

    ACTION_FIGHT_SPLASH_RAW_TAKEN_DAMAGE_NEUTRAL: int = 1124

    ACTION_FIGHT_SPLASH_RAW_TAKEN_DAMAGE_AIR: int = 1125

    ACTION_FIGHT_SPLASH_RAW_TAKEN_DAMAGE_FIRE: int = 1126

    ACTION_FIGHT_SPLASH_RAW_TAKEN_DAMAGE_WATER: int = 1127

    ACTION_FIGHT_SPLASH_RAW_TAKEN_DAMAGE_EARTH: int = 1128

    ACTION_CHARACTER_MANA_USE_KILL_LIFE_AIR: int = 1131

    ACTION_CHARACTER_MANA_USE_KILL_LIFE_WATER: int = 1132

    ACTION_CHARACTER_MANA_USE_KILL_LIFE_FIRE: int = 1133

    ACTION_CHARACTER_MANA_USE_KILL_LIFE_NEUTRAL: int = 1134

    ACTION_CHARACTER_MANA_USE_KILL_LIFE_EARTH: int = 1135

    ACTION_CHARACTER_MOVEMENT_USE_KILL_LIFE_AIR: int = 1136

    ACTION_CHARACTER_MOVEMENT_USE_KILL_LIFE_WATER: int = 1137

    ACTION_CHARACTER_MOVEMENT_USE_KILL_LIFE_FIRE: int = 1138

    ACTION_CHARACTER_MOVEMENT_USE_KILL_LIFE_NEUTRAL: int = 1139

    ACTION_CHARACTER_MOVEMENT_USE_KILL_LIFE_EARTH: int = 1140

    ACTION_ACHIEVEMENT_OBJECTIVE_VALIDATE: int = 1142

    ACTION_FIGHT_BOOST_WEAPON_DAMAGE_POWER: int = 1144

    ACTION_ITEM_ALLIANCE_EMBLEM_CHANGE: int = 1145

    ACTION_ITEM_ALLIANCE_RENAME: int = 1146

    ACTION_CHARACTER_GAIN_XP_WITH_LEVEL: int = 1149

    ACTION_REFRESH_ELEMENT: int = 1150

    ACTION_ITEM_MIMICRY_OBJ_GID: int = 1151

    ACTION_MARK_NOT_TRADABLE_BACKUP: int = 1152

    ACTION_ADD_TAX_COLLECTOR: int = 1153

    ACTION_ADD_PRISM_MODULE: int = 1154

    ACTION_ITEM_TELEPORT_MAP_REFERENCE_FORCE: int = 1155

    ACTION_CHARACTER_MULTIPLY_RECEIVED_HEAL: int = 1159

    ACTION_CASTER_EXECUTE_SPELL: int = 1160

    ACTION_SET_COMPANION: int = 1161

    ACTION_CHANGE_COMPASS_BY_REF: int = 1162

    ACTION_CHARACTER_MULTIPLY_RECEIVED_DAMAGE: int = 1163

    ACTION_CHARACTER_GIVE_LIFE_WITH_RATIO: int = 1164

    ACTION_FIGHT_ADD_GLYPH_CASTING_SPELL_IMMEDIATE: int = 1165

    ACTION_FIGHT_BOOST_GLYPH_DAMAGE_POWER: int = 1166

    ACTION_FIGHT_BOOST_RUNE_DAMAGE_POWER: int = 1167

    ACTION_GET_PORTAL_QUEST: int = 1168

    ACTION_USE_PORTAL: int = 1169

    ACTION_GET_TREASURE_QUEST: int = 1170

    ACTION_CHARACTER_BOOST_DEALT_DAMAGE_PERCENT_MULTIPLIER: int = 1171

    ACTION_CHARACTER_DEBOOST_DEALT_DAMAGE_PERCENT_MULTIPLIER: int = 1172

    ACTION_GET_LEGENDARY_TREASURE_QUEST: int = 1173

    ACTION_STOP_XP: int = 1174

    ACTION_CAST_STARTING_SPELL: int = 1175

    ACTION_ITEM_WRAPPER_LOOK_OBJ_GID: int = 1176

    ACTION_ITEM_TELEPORT_NEXT_MAP: int = 1177

    ACTION_ITEM_TELEPORT_PREVIOUS_MAP: int = 1178

    ACTION_ITEM_WRAPPER_COMPATIBLE_OBJ_TYPE: int = 1179

    ACTION_CHARACTER_READ_EXTERNAL_BOOK: int = 1180

    ACTION_FIGHT_ADD_PORTAL: int = 1181

    ACTION_FIGHT_USE_PORTAL: int = 1182

    ACTION_FIGHT_DISABLE_PORTAL: int = 1183

    ACTION_CHARACTER_GAIN_JOB_LEVEL_FROM_LEVEL_ONE: int = 1184

    ACTION_ITEM_RESET_EFFECTS: int = 1185

    ACTION_RIDE_HARNESS_GID: int = 1187

    ACTION_RIDE_GAIN_CAPACITY: int = 1188

    ACTION_CHARACTER_ADD_DOUBLE_NO_SUMMON_SLOT: int = 1189

    ACTION_FIGHT_SPLASH_FINAL_TAKEN_DAMAGE: int = 1223

    ACTION_FIGHT_SPLASH_FINAL_TAKEN_DAMAGE_NEUTRAL: int = 1224

    ACTION_FIGHT_SPLASH_FINAL_TAKEN_DAMAGE_AIR: int = 1225

    ACTION_FIGHT_SPLASH_FINAL_TAKEN_DAMAGE_FIRE: int = 1226

    ACTION_FIGHT_SPLASH_FINAL_TAKEN_DAMAGE_WATER: int = 1227

    ACTION_FIGHT_SPLASH_FINAL_TAKEN_DAMAGE_EARTH: int = 1228

    ACTION_TARGET_EXECUTE_SPELL_ON_SOURCE_GLOBAL_LIMITATION: int = 2017

    ACTION_DISPEL_GLYPHS_OF_TARGET: int = 2018

    ACTION_DISPEL_TRAPS_OF_TARGET: int = 2019

    ACTION_FIGHT_SPLASH_HEAL: int = 2020

    ACTION_NUGGETS_REPARTITION: int = 2021

    ACTION_FIGHT_ADD_RUNE_CASTING_SPELL: int = 2022

    ACTION_FORCE_RUNE_TRIGGER: int = 2023

    ACTION_DISPEL_RUNES_OF_TARGET: int = 2024

    ACTION_CHARACTER_OPEN_HAVENBAG_STORAGE: int = 2025

    ACTION_CHARACTER_HAVENBAG_LOTTERY: int = 2026

    ACTION_CONTROL_ENTITY: int = 2027

    ACTION_INHERITE_CHARAC: int = 2028

    ACTION_FINISH_MOVE: int = 2029

    ACTION_CHARACTER_LEARN_FINISH_MOVE: int = 2030

    ACTION_CHARACTER_LEARN_HAVEN_BAG_THEME: int = 2031

    ACTION_CASTER_EXECUTE_SPELL_GLOBAL_LIMITATION: int = 2160

    ACTION_TARGET_EXECUTE_SPELL_GLOBAL_LIMITATION: int = 2792

    ACTION_TARGET_EXECUTE_SPELL_WITH_ANIMATION_GLOBAL_LIMITATION: int = 2793

    ACTION_TARGET_EXECUTE_SPELL_ON_CELL: int = 2794

    ACTION_TARGET_EXECUTE_SPELL_ON_CELL_GLOBAL_LIMITATION: int = 2795

    ACTION_FIGHT_KILL_AND_SUMMON_SLAVE: int = 2796

    ACTION_CHARACTER_LEARN_SMILEY_PACK: int = 2797

    ACTION_CHARACTER_BOOST_DEALT_DAMAGE_PERCENT_MULTIPLIER_MELEE: int = 2800

    ACTION_CHARACTER_DEBOOST_DEALT_DAMAGE_PERCENT_MULTIPLIER_MELEE: int = 2801

    ACTION_CHARACTER_BOOST_RECEIVED_DAMAGE_PERCENT_MULTIPLIER_MELEE: int = 2802

    ACTION_CHARACTER_DEBOOST_RECEIVED_DAMAGE_PERCENT_MULTIPLIER_MELEE: int = 2803

    ACTION_CHARACTER_BOOST_DEALT_DAMAGE_PERCENT_MULTIPLIER_DISTANCE: int = 2804

    ACTION_CHARACTER_DEBOOST_DEALT_DAMAGE_PERCENT_MULTIPLIER_DISTANCE: int = 2805

    ACTION_CHARACTER_BOOST_RECEIVED_DAMAGE_PERCENT_MULTIPLIER_DISTANCE: int = 2806

    ACTION_CHARACTER_DEBOOST_RECEIVED_DAMAGE_PERCENT_MULTIPLIER_DISTANCE: int = 2807

    ACTION_CHARACTER_BOOST_DEALT_DAMAGE_PERCENT_MULTIPLIER_WEAPON: int = 2808

    ACTION_CHARACTER_DEBOOST_DEALT_DAMAGE_PERCENT_MULTIPLIER_WEAPON: int = 2809

    ACTION_CHARACTER_BOOST_RECEIVED_DAMAGE_PERCENT_MULTIPLIER_WEAPON: int = 2810

    ACTION_CHARACTER_DEBOOST_RECEIVED_DAMAGE_PERCENT_MULTIPLIER_WEAPON: int = 2811

    ACTION_CHARACTER_BOOST_DEALT_DAMAGE_PERCENT_MULTIPLIER_SPELLS: int = 2812

    ACTION_CHARACTER_DEBOOST_DEALT_DAMAGE_PERCENT_MULTIPLIER_SPELLS: int = 2813

    ACTION_CHARACTER_BOOST_RECEIVED_DAMAGE_PERCENT_MULTIPLIER_SPELLS: int = 2814

    ACTION_CHARACTER_DEBOOST_RECEIVED_DAMAGE_PERCENT_MULTIPLIER_SPELLS: int = 2815

    ACTION_BOOST_CHARAC_CONVERT: int = 2816

    ACTION_BUY_IN_BID_HOUSE: int = 2817

    ACTION_HOME_MADE: int = 2818

    ACTION_EVOLUTIVE_OBJECT_EXPERIENCE: int = 2819

    ACTION_SUPERFOOD_EXPERIENCE: int = 2820

    ACTION_EVOLUTIVE_PET_LEVEL: int = 2821

    ACTION_CHARACTER_LIFE_POINTS_LOST_FROM_BEST_ELEMENT: int = 2822

    ACTION_CHARACTER_PLAY_EMOTICON: int = 2823

    ACTION_BOOST_ALL_SPELL_BASE_DMG: int = 2824

    PREVENT_FUTURE_SMITHMAGIC: int = 2825

    SMITHMAGIC_FORCE_WEIGHT: int = 2826

    SMITHMAGIC_FORCE_PROBABILITY: int = 2827

    ACTION_CHARACTER_LIFE_POINTS_STEAL_FROM_BEST_ELEMENT: int = 2828

    ACTION_FIGHT_SPLASH_RAW_TAKEN_DAMAGE_BEST_ELEMENT: int = 2829

    ACTION_FIGHT_SPLASH_FINAL_TAKEN_DAMAGE_BEST_ELEMENT: int = 2830

    WIPWIPWIP: int = 2831

    ACTION_ITEM_EXPIRATION: int = 2833

    ACTION_CHARACTER_BOOST_STRENGTH_PERCENT: int = 2834

    ACTION_CHARACTER_DEBOOST_STRENGTH_PERCENT: int = 2835

    ACTION_CHARACTER_BOOST_AGILITY_PERCENT: int = 2836

    ACTION_CHARACTER_DEBOOST_AGILITY_PERCENT: int = 2837

    ACTION_CHARACTER_BOOST_INTELLIGENCE_PERCENT: int = 2838

    ACTION_CHARACTER_DEBOOST_INTELLIGENCE_PERCENT: int = 2839

    ACTION_CHARACTER_BOOST_CHANCE_PERCENT: int = 2840

    ACTION_CHARACTER_DEBOOST_CHANCE_PERCENT: int = 2841

    ACTION_CHARACTER_BOOST_WISDOM_PERCENT: int = 2842

    ACTION_CHARACTER_DEBOOST_WISDOM_PERCENT: int = 2843

    ACTION_CHARACTER_BOOST_VITALITY_PERCENT: int = 2844

    ACTION_CHARACTER_DEBOOST_VITALITY_PERCENT: int = 2845

    ACTION_CHARACTER_BOOST_ACTION_POINTS_PERCENT: int = 2846

    ACTION_CHARACTER_DEBOOST_ACTION_POINTS_PERCENT: int = 2847

    ACTION_CHARACTER_BOOST_MOVEMENT_POINTS_PERCENT: int = 2848

    ACTION_CHARACTER_DEBOOST_MOVEMENT_POINTS_PERCENT: int = 2849

    ACTION_CHARACTER_BOOST_TAKLE_BLOCK_PERCENT: int = 2850

    ACTION_CHARACTER_DEBOOST_TAKLE_BLOCK_PERCENT: int = 2851

    ACTION_CHARACTER_BOOST_TAKLE_EVADE_PERCENT: int = 2852

    ACTION_CHARACTER_DEBOOST_TAKLE_EVADE_PERCENT: int = 2853

    ACTION_CHARACTER_BOOST_ACTION_POINTS_LOST_DODGE_PERCENT: int = 2854

    ACTION_CHARACTER_DEBOOST_ACTION_POINTS_LOST_DODGE_PERCENT: int = 2855

    ACTION_CHARACTER_BOOST_MOVEMENT_POINTS_LOST_DODGE_PERCENT: int = 2856

    ACTION_CHARACTER_DEBOOST_MOVEMENT_POINTS_LOST_DODGE_PERCENT: int = 2857

    ACTION_CHARACTER_BOOST_AP_ATTACK_PERCENT: int = 2858

    ACTION_CHARACTER_DEBOOST_AP_ATTACK_PERCENT: int = 2859

    ACTION_CHARACTER_BOOST_MP_ATTACK_PERCENT: int = 2860

    ACTION_CHARACTER_DEBOOST_MP_ATTACK_PERCENT: int = 2861

    ACTION_LEGENDARY_STATUS: int = 2862

    ACTION_LEGENDARY_POWER_SPELL: int = 2864

    ACTION_CHARACTER_GAIN_XP_WO_BOOST: int = 2865

    ACTION_NO_SYSTEM_SAVE: int = 2866

    ACTION_CHARACTER_BOOST_XP_COEFF: int = 2867

    ACTION_CHARACTER_ADD_SCALE_PERCENT: int = 2868

    ACTION_CHARACTER_BOOST_JOB_XP_COEFF: int = 2869

    PAY_LEAVE_JAIL: int = 2870

    ACTION_CHARACTER_LOWER_SCALE_PERCENT: int = 2871

    ACTION_CHARACTER_BOOST_THRESHOLD: int = 2872

    ACTION_BREACH_RESET_ROOM_SEED: int = 2873

    ACTION_BREACH_RESET_ROOM_CHALLENGE: int = 2874

    ACTION_CHARACTER_LEARN_SPELL_FORGETTABLE: int = 2875

    ACTION_FIGHT_VALIDATE_CHALLENGE: int = 2876

    ACTION_FIGHT_INVALIDATE_CHALLENGE: int = 2877

    ACTION_GAIN_LEVEL: int = 2878

    ACTION_CHARACTER_INVENTORY_ADD_PERFECT_ITEM_CHECK: int = 2879

    ACTION_ITEM_CUSTOM_EFFECT: int = 2880

    ACTION_SELF_PILOTING: int = 2881

    ACTION_DISTRIBUTE_GAMEACTION: int = 2882
