from enum import Enum


class DataEnum(Enum):

    BREED_PANDAWA: int = 12

    BREED_ROGUE: int = 13

    BREED_MASQUERAIDER: int = 14

    JOB_ID_BASE: int = 1

    JOB_ID_HUNTER: int = 41

    HINT_CATEGORY_TEMPLES: int = 1

    HINT_CATEGORY_BIDHOUSE: int = 2

    HINT_CATEGORY_CRAFT_HOUSES: int = 3

    HINT_CATEGORY_MISC: int = 4

    HINT_CATEGORY_DUNGEONS: int = 6

    HINT_CATEGORY_TRANSPORTATIONS: int = 9

    ITEM_SUPERTYPE_COLLAR: int = 1

    ITEM_SUPERTYPE_WEAPON: int = 2

    ITEM_SUPERTYPE_RING: int = 3

    ITEM_SUPERTYPE_BELT: int = 4

    ITEM_SUPERTYPE_SHOES: int = 5

    ITEM_SUPERTYPE_CONSUMABLE: int = 6

    ITEM_SUPERTYPE_SHIELD: int = 7

    ITEM_SUPERTYPE_CATCHING_ITEMS: int = 8

    ITEM_SUPERTYPE_RESOURCES: int = 9

    ITEM_SUPERTYPE_HELMET: int = 10

    ITEM_SUPERTYPE_CAPE: int = 11

    ITEM_SUPERTYPE_PET: int = 12

    ITEM_SUPERTYPE_DOFUS_TROPHY: int = 13

    ITEM_SUPERTYPE_QUEST_ITEMS: int = 14

    ITEM_SUPERTYPE_MUTATIONS: int = 15

    ITEM_SUPERTYPE_FOODS: int = 16

    ITEM_SUPERTYPE_BLESSINGS: int = 17

    ITEM_SUPERTYPE_CURSES: int = 18

    ITEM_SUPERTYPE_ROLEPLAY_BUFFS: int = 19

    ITEM_SUPERTYPE_FOLLOWERS: int = 20

    ITEM_SUPERTYPE_MOUNTS: int = 21

    ITEM_SUPERTYPE_LIVING_ITEMS: int = 22

    ITEM_SUPERTYPE_COMPANION: int = 23

    ITEM_SUPERTYPE_MOUNT_EQUIPMENT: int = 24

    ITEM_SUPERTYPE_COSTUME: int = 25

    ITEM_SUPERTYPE_CERTIFICATE: int = 27

    ITEM_SUPERTYPE_PET_GHOST: int = 28

    ITEM_TYPE_COLLAR: int = 1

    ITEM_TYPE_BOW: int = 2

    ITEM_TYPE_ROD: int = 3

    ITEM_TYPE_STAFF: int = 4

    ITEM_TYPE_DAGGER: int = 5

    ITEM_TYPE_SWORD: int = 6

    ITEM_TYPE_HAMMER: int = 7

    ITEM_TYPE_SHOVEL: int = 8

    ITEM_TYPE_RING: int = 9

    ITEM_TYPE_BELT: int = 10

    ITEM_TYPE_SHOES: int = 11

    ITEM_TYPE_HAT: int = 16

    ITEM_TYPE_CLOAK: int = 17

    ITEM_TYPE_PET: int = 18

    ITEM_TYPE_AXE: int = 19

    ITEM_TYPE_PICKAXE: int = 21

    ITEM_TYPE_SCYTHE: int = 22

    ITEM_TYPE_SMITHMAGIC_POTION: int = 26

    ITEM_TYPE_MUTATIONS: int = 27

    ITEM_TYPE_MEAT: int = 63

    ITEM_TYPE_PET_EGG: int = 72

    ITEM_TYPE_SMITHMAGIC_RUNE: int = 78

    ITEM_TYPE_DRINK: int = 79

    ITEM_TYPE_BACKPACK: int = 81

    ITEM_TYPE_SHIELD: int = 82

    ITEM_TYPE_EMPTY_SOULSTONE: int = 83

    ITEM_TYPE_SOULSTONE: int = 85

    ITEM_TYPE_BREEDING_ITEM: int = 93

    ITEM_TYPE_DRAGOTURKEY_CERTIFICATE: int = 97

    ITEM_TYPE_CATCHING_NET: int = 99

    ITEM_TYPE_CROSSBOW: int = 102

    ITEM_TYPE_WING: int = 104

    ITEM_TYPE_PET_POTION: int = 116

    ITEM_TYPE_LIVING_OBJECT: int = 113

    ITEM_TYPE_MAGIC_WEAPON: int = 114

    ITEM_TYPE_HIDDEN: int = 118

    ITEM_TYPE_PETSMOUNT: int = 121

    ITEM_TYPE_PETSMOUNT_POTION: int = 122

    ITEM_TYPE_TROPHY: int = 151

    ITEM_TYPE_MIMISYMBIC: int = 166

    ITEM_TYPE_COMPANION: int = 169

    ITEM_TYPE_CEREMONIAL_ITEMS: int = 177

    ITEM_TYPE_IDOLS: int = 178

    ITEM_TYPE_SMITHMAGIC_ORB: int = 189

    ITEM_TYPE_HARNESS_MOUNT: int = 190

    ITEM_TYPE_MULDO_CERTIFICATE: int = 196

    ITEM_TYPE_RECEIPT: int = 197

    ITEM_TYPE_COSMETIC_COSTUME: int = 199

    ITEM_TYPE_MOUNT_POTION: int = 206

    ITEM_TYPE_FLYHORN_CERTIFICATE: int = 207

    ITEM_TYPE_SMITHMAGIC_TRANSCENDANCE_RUNE: int = 211

    ITEM_TYPE_SMITHMAGIC_CORRUPTION_RUNE: int = 212

    ITEM_TYPE_PRYSMARADITE: int = 217

    ITEM_TYPE_HAVENBAG: int = 218

    ITEM_TYPE_COSMETIC_HAT: int = 246

    ITEM_TYPE_COSMETIC_CLOAK: int = 247

    ITEM_TYPE_COSMETIC_SHIELD: int = 248

    ITEM_TYPE_COSMETIC_PET: int = 249

    ITEM_TYPE_COSMETIC_PETMOUNT: int = 250

    ITEM_TYPE_COSMETIC_WEAPON: int = 251

    ITEM_TYPE_COSMETIC_MISC: int = 252

    ITEM_TYPE_HARNESS_MULDO: int = 255

    ITEM_TYPE_HARNESS_FLYHORN: int = 256

    ITEM_TYPE_FORGETTABLE_SPELL_SCROLL: int = 223

    ITEM_TYPE_FORGETTABLE_HIDDEN_SPELL: int = 224

    ITEM_TYPE_TEMPORIS_RICHETON_BAG: int = 226

    ITEM_TYPE_MINOUKI: int = 240

    ITEM_TYPE_ECAFLIP_CARD: int = 238

    ITEM_GID_SOULSTONE: int = 7010

    ITEM_GID_SIGNATURE_RUNE: int = 7508

    ITEM_GID_HUNTING_RUNE: int = 10057

    ITEM_GID_SOULSTONE_BOSS: int = 10417

    ITEM_GID_SOULSTONE_MINIBOSS: int = 10418

    ITEM_GID_PRESET_SHORTCUT: int = 11589

    ITEM_GID_DOLMANAX: int = 13344

    ITEM_GID_CALENDAR_PAGE: int = 13345

    ITEM_GID_TELEPORTATION_MODULE: int = 14552

    ITEM_GID_NUGGET: int = 14635

    ITEM_GID_SANDS_ROSE: int = 15263

    ITEM_GID_BREACH_FRAGMENTS: int = 20292

    ACTION_TYPE_CARACTERISTICS: int = 0

    ACTION_TYPE_DAMAGES: int = 2

    ACTION_TYPE_STATUS: int = 4

    SERVER_COMMUNITY_FRENCH_SPEAKING: int = 0

    SERVER_COMMUNITY_ENGLISH_SPEAKING: int = 1

    SERVER_COMMUNITY_INTERNATIONAL_ALL_EXCEPT_FRENCH: int = 2

    SERVER_COMMUNITY_SPANISH_SPEAKING: int = 4

    SERVER_COMMUNITY_INTERNATIONAL_ALL: int = 12

    SERVER_COMMUNITY_BETA: int = 100

    SKILL_LOCK_HOUSE: int = 81

    SKILL_BUY_HOUSE: int = 97

    SKILL_SELL_HOUSE: int = 98

    SKILL_UNLOCK_HOUSE: int = 100

    SKILL_CHANGE_PRICE_HOUSE: int = 108

    SKILL_MAGE_SHOES: int = 164

    SKILL_MAGE_TAILOR: int = 166

    SKILL_MAGE_JEWEL: int = 168

    SKILL_ACCESS_PADDOCK: int = 175

    SKILL_BUY_PADDOCK: int = 176

    SKILL_SHATTER_ITEM: int = 181

    SKILL_WRAP_GIFT: int = 209

    SKILL_POINT_OUT_EXIT: int = 339

    SKILL_SIGN_FREE_TEXT: int = 360

    SKILL_SIGN_HINT: int = 361

    SKILL_SIGN_SUBAREA: int = 362

    SKILL_CHINQ: int = 397

    SKILL_MINOUKI: int = 398

    TEXT_NOTIFICATION_SERVER_INFORMATION: int = 24

    TEXT_NOTIFICATION_SERVER_KOLOSSIUM: int = 33

    TEXT_NOTIFICATION_SERVER_GIFT: int = 34

    TEXT_NOTIFICATION_SERVER_KOTH_SUPERIORITY: int = 36

    WORLD_AMAKNA_DEFAULT: int = 0

    WORLD_DEBUG: int = 1

    WORLD_TEST: int = 2

    WORLD_STARTZONE: int = 3

    AREA_INCARNAM: int = 45

    SUBAREA_TUTORIAL: int = 536

    SUBAREA_INFINITE_BREACH: int = 904

    SPELL_SRAM_DOUBLE: int = 12915

    SPELL_SRAM_TRAPS: int = 9846

    SPELL_TYPE_TEST: int = 29

    SPELL_TYPE_SPECIALS: int = 24

    SPELL_TYPE_INCARNATION: int = 32

    SPELL_STATE_ROOTED: int = 6

    SPELL_STATE_CARRIED: int = 8

    SPELL_STATE_INVULNERABLE: int = 56

    SPELL_STATE_UNHEALABLE: int = 76

    SPELL_STATE_CANT_LOCK: int = 95

    SPELL_STATE_ARCHER: int = 101

    SPELL_STATE_CANT_BE_LOCKED: int = 96

    SPELL_STATE_TELEFRAG_ALLY: int = 244

    CHAT_CHANNEL_GENERAL: int = 0

    CHAT_CHANNEL_TEAM: int = 1

    CHAT_CHANNEL_GUILD: int = 2

    CHAT_CHANNEL_ALLIANCE: int = 3

    CHAT_CHANNEL_GROUP: int = 4

    CHAT_CHANNEL_TRADE: int = 5

    CHAT_CHANNEL_RECRUITMENT: int = 6

    CHAT_CHANNEL_NOOB: int = 7

    CHAT_CHANNEL_ADMIN: int = 8

    CHAT_CHANNEL_PRIVATE: int = 9

    CHAT_CHANNEL_INFORMATION: int = 10

    CHAT_CHANNEL_FIGHT: int = 11

    CHAT_CHANNEL_PROMOTIONAL: int = 12

    CHAT_CHANNEL_ARENA: int = 13

    CHAT_CHANNEL_COMMUNITY: int = 14

    MOUNT_CAPACITY_AUTOPILOT: int = 10

    CHARACTERISTIC_TYPE_PRIMARY: int = 2

    SHORTCUT_TYPE_ITEM: int = 0

    SHORTCUT_TYPE_PRESET: int = 1

    SHORTCUT_TYPE_SPELL: int = 2

    SHORTCUT_TYPE_SMILEY: int = 3

    SHORTCUT_TYPE_EMOTE: int = 4

    SHORTCUT_TYPE_IDOLS_PRESET: int = 5

    BREACH_REWARD_CURRENCY_BUDGET: int = 0

    SOCIAL_TAB_LAST_OPENED_ID: int = -1

    SOCIAL_TAB_FRIENDS_ID: int = 0

    SOCIAL_TAB_GUILD_ID: int = 1

    SOCIAL_TAB_GUILD_DIRECTORY_ID: int = 4

    SOCIAL_TAB_ALLIANCE_ID: int = 2

    SOCIAL_TAB_ALLIANCE_DIRECTORY_ID: int = 5

    SOCIAL_TAB_SPOUSE_ID: int = 3

    GUILD_TAB_MEMBERS_ID: int = 0

    GUILD_TAB_PERSONALIZATION_ID: int = 1

    GUILD_TAB_COLLECTOR_ID: int = 2

    GUILD_TAB_PADDOCK_ID: int = 3

    GUILD_TAB_HOUSES_ID: int = 4

    GUILD_TAB_BULLETIN_ID: int = 5

    GUILD_TAB_DIRECTORY_ID: int = 6

    ALLIANCE_TAB_MEMBERS_ID: int = 0

    ALLIANCE_TAB_AREAS_ID: int = 1

    ALLIANCE_TAB_FIGHTS_ID: int = 2

    ALLIANCE_TAB_BULLETIN_ID: int = 3

    ALLIANCE_TAB_DIRECTORY_ID: int = 4

    BREACH_REWARD_ADD_BOSS: int = 6

    CHARAC_HEALTH_POINT_ID: int = 0

    CHARAC_MOVEMENT_POINT_ID: int = 23

    CHARAC_RANGE_ID: int = 19

    CHARAC_VITALITY_ID: int = 11

    BREEDING_ITEM_ENERGY_BASE_SPELL_ID: int = 208

    BREEDING_ITEM_MATURY_BASE_SPELL_ID: int = 207

    BREEDING_ITEM_AGGRO_BASE_SPELL_ID: int = 204

    BREEDING_ITEM_SERENITY_BASE_SPELL_ID: int = 203

    BREEDING_ITEM_LOVE_BASE_SPELL_ID: int = 206

    BREEDING_ITEM_STAMINA_BASE_SPELL_ID: int = 205

    BREEDING_ITEM_REMOVE_OBJECT_BASE_SPELL_ID: int = 197

    CARD_SUPER_EFFECT_ID: int = 3

    MINOUKI_SUPER_EFFECT_ID: int = 4

    CARD_BONUS_CUSTOM_EFFECT_ID: int = 5

    CARD_HEART_CUSTOM_EFFECT_ID: int = 6

    CARD_DIAMOND_CUSTOM_EFFECT_ID: int = 7

    CARD_SPADE_CUSTOM_EFFECT_ID: int = 8

    CARD_CLUB_CUSTOM_EFFECT_ID: int = 9

    LOCATION_BONUS_CUSTOM_EFFECT_ID: int = 10

    LOCATION_HEART_CUSTOM_EFFECT_ID: int = 11

    LOCATION_DIAMOND_CUSTOM_EFFECT_ID: int = 12

    LOCATION_SPADE_CUSTOM_EFFECT_ID: int = 13

    LOCATION_CLUB_CUSTOM_EFFECT_ID: int = 14
