class ProtocolConstantsEnum:

    DEFAULT_TOOLTIP_DURATION: int = 2500

    MAP_CELL_COUNT: int = 560

    MAX_LEVEL: int = 200

    MAX_GUILD_LEVEL: int = 200

    MAX_MOUNT_LEVEL: int = 100

    MAX_CMD_LEN: int = 768

    MAX_CHAT_LEN: int = 512

    USER_MAX_CHAT_LEN: int = 256

    MAX_MOTD_LEN: int = 512

    USER_MAX_MOTD_LEN: int = 256

    MAX_BULLETIN_LEN: int = 5120

    USER_MAX_BULLETIN_LEN: int = 2560

    MAX_STAT_LEN: int = 512

    MAX_STAT_BY_MSG: int = 20

    MIN_LOGIN_LEN: int = 3

    MAX_LOGIN_LEN: int = 50

    MIN_PLAYER_NAME_LEN: int = 2

    MAX_PLAYER_NAME_LEN: int = 26

    PLAYER_SERVER_TAG_LEN: int = 6

    MIN_NICK_LEN: int = 2

    MAX_NICK_LEN: int = 30

    MIN_ACCOUNT_NAME_LEN: int = 3

    MAX_ACCOUNT_NAME_LEN: int = 31

    ACCOUNT_TAG_LEN: int = 4

    MIN_GUILDNAME_LEN: int = 3

    MAX_GUILDNAME_LEN: int = 30

    MIN_ALLIANCENAME_LEN: int = 3

    MAX_ALLIANCENAME_LEN: int = 30

    MIN_ALLIANCETAG_LEN: int = 3

    MAX_ALLIANCETAG_LEN: int = 7

    ALLIANCETAG_NUMBER_LEN: int = 2

    MIN_PARTY_NAME_LEN: int = 0

    MAX_PARTY_NAME_LEN: int = 25

    MAX_PLAYER_COLOR: int = 5

    MAX_ENTITY_COLOR: int = 10

    MAX_PLAYERS_PER_TEAM: int = 8

    MAX_MEMBERS_PER_PARTY: int = 8

    MAX_GUESTS_PER_PARTY: int = 7

    MAX_MEMBERS_PER_ARENA_PARTY: int = 5

    MAX_MONSTERS_IN_GROUP_ON_MAP: int = 16

    MAX_CHAT_OBJECT_REF: int = 16

    NOT_EQUIPED: int = 63

    MAX_EQUIPED: int = 255

    SLOTS_EQUIPABLE_BY_USER: int = 16

    MAX_CRAFT_SLOT: int = 9

    MAX_JOB_LEVEL: int = 200

    MAX_JOB_LEVEL_NONSUBSCRIBER: int = 60

    MAX_HONOR: int = 20000

    MAX_SHORTCUT: int = 99

    MAX_ARENA_RANK: int = 20000

    CHAR_MIN_LEVEL_ARENA: int = 20

    CHAR_MIN_LEVEL_RIDE: int = 60

    MAX_DUNGEON_REGISTER: int = 10

    MIN_RIDE_NAME_LEN: int = 0

    MAX_RIDE_NAME_LEN: int = 16

    MAX_EFFECTS_COUNT: int = 150

    MAX_LOCKABLE_CODE_LEN: int = 8

    MAX_PRESET_COUNT: int = 18

    MAX_IDOLS_PRESET_IDOL_COUNT: int = 6

    MIN_OBJ_COUNT_BY_XFERT: int = 1

    MAX_OBJ_COUNT_BY_XFERT: int = 800

    MAX_FARMS_INSTANCES_PER_MAP: int = 60

    MAX_STABLED_RIDES: int = 250

    MAX_OBJ_COUNT_BY_DECRAFT: int = 50

    MAX_WAVE: int = 100

    MAX_OBJECT_EFFECT_STRING_LEN: int = 30

    MAX_MEMBERS_PER_GUILD: int = 240

    MAX_GUILD_PER_PAGE: int = 50

    MAX_GUILD_APPLICATION_PER_PAGE: int = 50

    MAX_ADDITIONNAL_PER_CARAC: int = 100

    MAX_RECONNECTION_ATTEMPTS: int = 5

    MAX_FURNITURES_PER_PACKET: int = 40

    MIN_LEVEL_HAVENBAG: int = 10

    MIN_PLAYERS_FOR_GROUP_IDOLS: int = 3

    MAX_KAMA: float = 1000000000000

    MAX_FOLLOWED_QUESTS: int = 10

    MIN_LEVEL_BREACH: int = 50

    MIN_EMAIL_LENGTH: int = 3

    MAX_EMAIL_LENGTH: int = 254

    UUID5_LENGTH: int = 36

    MAX_SHORT_VALUE: int = 32767
