from enum import Enum


class CharacterInventoryPositionEnum(Enum):

    ACCESSORY_POSITION_HAT: int = 6

    ACCESSORY_POSITION_CAPE: int = 7

    ACCESSORY_POSITION_BELT: int = 3

    ACCESSORY_POSITION_BOOTS: int = 5

    ACCESSORY_POSITION_AMULET: int = 0

    ACCESSORY_POSITION_SHIELD: int = 15

    ACCESSORY_POSITION_WEAPON: int = 1

    ACCESSORY_POSITION_PETS: int = 8

    ACCESSORY_POSITION_RIDE_HARNESS: int = 29

    INVENTORY_POSITION_RING_LEFT: int = 2

    INVENTORY_POSITION_RING_RIGHT: int = 4

    INVENTORY_POSITION_DOFUS_1: int = 9

    INVENTORY_POSITION_DOFUS_2: int = 10

    INVENTORY_POSITION_DOFUS_3: int = 11

    INVENTORY_POSITION_DOFUS_4: int = 12

    INVENTORY_POSITION_DOFUS_5: int = 13

    INVENTORY_POSITION_DOFUS_6: int = 14

    INVENTORY_POSITION_MOUNT: int = 16

    INVENTORY_POSITION_MUTATION: int = 20

    INVENTORY_POSITION_BOOST_FOOD: int = 21

    INVENTORY_POSITION_FIRST_BONUS: int = 22

    INVENTORY_POSITION_SECOND_BONUS: int = 23

    INVENTORY_POSITION_FIRST_MALUS: int = 24

    INVENTORY_POSITION_SECOND_MALUS: int = 25

    INVENTORY_POSITION_ROLEPLAY_BUFFER: int = 26

    INVENTORY_POSITION_FOLLOWER: int = 27

    INVENTORY_POSITION_ENTITY: int = 28

    INVENTORY_POSITION_COSTUME: int = 30

    INVENTORY_POSITION_NOT_EQUIPED: int = 63
